version: 2.1

orbs:
  cypress: cypress-io/cypress@2.2.0
  docker: circleci/docker@2.1.3

jobs:
  unit-tests:
    machine:
      image: ubuntu-2204:2022.07.1
      docker_layer_caching: true
    resource_class: medium
    steps:
      - checkout
      - run: cd packages/frontend && yarn && yarn test:coverage

  up-backend:
    machine:
      image: ubuntu-2204:2022.07.1
      docker_layer_caching: true
    resource_class: medium
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - run: sudo apt install -y docker-compose
      - run: docker-compose -f packages/backend/docker-compose.yml up -d
  
  e2e-tests:
    machine:
      image: ubuntu-2204:2022.07.1
      docker_layer_caching: true
    resource_class: medium
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - run: sudo apt install -y docker-compose
      - run: docker-compose -f packages/backend/docker-compose.yml up -d
      # - run: yarn global add cypress@10.7.0
      - run: cd packages/frontend && yarn && yarn dev &
      - run: ls -lah && cp -R node_modules packages/frontend/node_modules
      - run: cd packages/frontend/ && yarn cypress run
  your-job:
    executor:
      name: docker/docker
      tag: '3.6'
    steps:
      - checkout
      - docker/install-docker-tools

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build:
    jobs:
      # - unit-tests
      - cypress/run:
          yarn: true
          working_directory: packages/frontend
          executor: cypress/base-16-14-2-slim
          start: cd packages/backend &&
                  pwd && ls -lah &&
                  yarn &&
                  yarn build &&
                  yarn dev &
                  cd ../frontend &&
                  pwd && ls -lah &&
                  yarn & yarn dev

  # orb-free-workflow:
  #   jobs:
  #     - unit-tests
  #     # - e2e-tests
