version: 2.1

orbs:
  cypress: cypress-io/cypress@2.2.0

jobs:
  unit-tests:
    machine:
      image: ubuntu-2204:2022.07.1
      docker_layer_caching: true
    resource_class: medium
    steps:
      - checkout
      - run: cd packages/frontend && yarn && yarn test:coverage

workflows:
  build:
    jobs:
      - unit-tests
      - cypress/run:
          yarn: true
          working_directory: packages/frontend
          executor: cypress/base-16-14-2-slim
          start: cd ../backend &&
                  yarn &&
                  yarn build &&
                  yarn dev &
                  cd ../frontend &&
                  yarn & yarn dev

