on:
  pull_request:
    branches:
      - main
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: circleci-shortme
        id: circleci-shortme
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
