name: Cypress Tests

on:
  pull_request:
    branches: ["hml"]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Install Cypress Dependencies
        run: sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - name: Install docker compose
        run: sudo apt install -y docker-compose

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run docker images
        run: |
          cd ./packages/backend
          docker-compose up -d
          cd ../../

      - name: Run Cypress
        run: |
          cd ./packages/frontend
          yarn
          yarn dev & yarn cypress run
