name: Embold

on:
  workflow_dispatch:
    inputs:
      container_name:
        description: "Manually run Cypress test"
        default: "henriquemod/shortme-backend"
        required: true
jobs:
  embold_scan_job:
    runs-on: ubuntu-latest
    name: Embold scan
    steps:
      - uses: actions/checkout@v2
      - uses: actions/embold-github-action@v1
      - with:
        emboldUrl: ${{ secrets.EMB_URL }}
        emboldToken: ${{ secrets.EMB_TOKEN }}
        emboldRepoUid: ${{ secrets.EMB_REPOUID }}
