name: Loading Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  k6_transpile_bundle_test:
    name: Transpile, bundle and run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download K6
        run: |
          curl https://github.com/loadimpact/k6/releases/download/v0.26.2/k6-v0.26.2-linux64.tar.gz -L | tar xvz --strip-components 1

      - name: Install dependencies
        run: |
          cd packages/loadingtest
          yarn --frozen-lockfile

      - name: Transpile and bundle test script
        run: |
          cd packages/loadingtest
          yarn webpack

      - name: Build backend and run K6
        run: |
          docker network create -d bridge shortme-network
          docker run -d --name postgres --network=shortme-network -e POSTGRES_PASSWORD=123456 postgres:11.13
          docker run -d --name shortme-backend --restart=always --network=shortme-network -p8080:8080 -e PORT=8080 -e NODE_ENV=hml henriquemod/shortme-backend:latest
          docker run -d --network=shortme-network -p80:80 -v $(pwd)/packages/backend/nginx/local.conf:/etc/nginx/conf.d/default.conf nginx
          curl https://github.com/grafana/k6/releases/download/v0.40.0/k6-v0.40.0-linux-amd64.tar.gz -L | tar xvz --strip-components 1
          K6_VUS=${{ secrets.K6_VUS }} K6_TIME=${{ secrets.K6_TIME }} ./k6 run ./packages/loadingtest/dist/index.js
