on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  k6_transpile_bundle_test:
    name: K6 - Transpile, bundle and run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run docker images
        run: |
          docker run -d --rm -e POSTGRES_PASSWORD=123456 -p5432:5432 postgres:11.13
          docker run -d --rm -e PORT=8080 -e NODE_ENV=hml -p8080:8080 henriquemod/shortme-backend

      - name: Install dependencies
        run: |
          cd packages/loadingtest
          yarn --frozen-lockfile

      - name: Transpile and bundle test script
        run: |
          cd packages/loadingtest
          yarn webpack

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: packages/loadingtest/dist/index.js
