name: PR Check and Tests

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  pr_check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: PR Check with Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn
      
      - name: Backend PR Check
        run: |
          cd ./packages/backend
          yarn lint
          yarn type-check

      - name: Frontend PR Check
        run: |
          cd ./packages/frontend
          yarn lint
          yarn type-check

  unit_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unit Tests with Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Frontend Unit Test
        run: |
          cd ./packages/frontend
          yarn lint
          yarn type-check

      - name: Frontend Unit Test
        run: |
          cd ./packages/backend
          yarn lint
          yarn type-check

      - name: Backend Unit Test using Node ${{ matrix.node-version }}
        run: |
          cd ./packages/backend
          NODE_ENV=development yarn test:ci

      - name: Frontend Unit Test using Node ${{ matrix.node-version }}
        run: |
          cd ./packages/frontend
          yarn test:coverage
