name: PR Check

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  check:
    name: PR Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd packages/frontend
          yarn --frozen-lockfile

      - name: Frontend Check
        run: |
          cd packages/frontend
          yarn lint
          type-check

      - name: Backend Check
        run: |
          cd packages/backend
          yarn lint
          type-check
